// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-GslhltUcjnJyrqgI0-zqibPGivi9hg',
    appId: '1:966231741983:web:e6b76338793d4b08c0a72a',
    messagingSenderId: '966231741983',
    projectId: 'rental-motor-14f6b',
    authDomain: 'rental-motor-14f6b.firebaseapp.com',
    databaseURL: 'https://rental-motor-14f6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-motor-14f6b.appspot.com',
    measurementId: 'G-XB5Z22LYP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFORJ_1_7xDOOBRrQoAheTQyQCKv7ZV74',
    appId: '1:966231741983:android:08db09741f1553dec0a72a',
    messagingSenderId: '966231741983',
    projectId: 'rental-motor-14f6b',
    databaseURL: 'https://rental-motor-14f6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-motor-14f6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMW7esO2VW57cMZIOB4cIrg5UwKVYEWlc',
    appId: '1:966231741983:ios:a510bad70c764216c0a72a',
    messagingSenderId: '966231741983',
    projectId: 'rental-motor-14f6b',
    databaseURL: 'https://rental-motor-14f6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-motor-14f6b.appspot.com',
    iosBundleId: 'com.example.learnFirebase3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMW7esO2VW57cMZIOB4cIrg5UwKVYEWlc',
    appId: '1:966231741983:ios:a510bad70c764216c0a72a',
    messagingSenderId: '966231741983',
    projectId: 'rental-motor-14f6b',
    databaseURL: 'https://rental-motor-14f6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-motor-14f6b.appspot.com',
    iosBundleId: 'com.example.learnFirebase3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo-GslhltUcjnJyrqgI0-zqibPGivi9hg',
    appId: '1:966231741983:web:78d1b6ea1011e1a3c0a72a',
    messagingSenderId: '966231741983',
    projectId: 'rental-motor-14f6b',
    authDomain: 'rental-motor-14f6b.firebaseapp.com',
    databaseURL: 'https://rental-motor-14f6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-motor-14f6b.appspot.com',
    measurementId: 'G-K29XSKLGYS',
  );
}
